export const candidatePositions = [
  'President',
  'Vice President',
  'Secretary',
  'Deputy Secretary',
  'Treasurer',
  'Deputy Treasurer',
  'Organizer',
  "Women's Organizer",
  'Deputy Organizer',
  'Wocom',
  'Deputy Wocom',
  'Communication Officer',
  'Deputy Communications Officer',
];